# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 111
  CLOUD_SQL_DATABASE_NAME: PromptsSchema
  CLOUD_SQL_CONNECTION_NAME: trivai-377917:us-central1:trivai-377917
# [END gae_python37_cloudsql_config]